### ISSUE TITLE
群晖的Docker中处理TTS请求时ParserOnHeaders崩溃

### ISSUE THREAD

**Issue by dustookk** [idootop/mi-gpt-tts#12]
您好，我也出现了和 [issue](https://github.com/idootop/mi-gpt-tts/issues/11) 一样的问题

<img width="821" alt="image" src="https://github.com/user-attachments/assets/5fffe8a5-c04f-4e93-8ddd-b71864a4ea02">

mi-gpt + mi-gpt-tts 标准配置方式：

请问作者本地是如何解决这个问题的？后续是否会提交修复方案。

```yaml

services:
  mi-gpt:
    image: idootop/mi-gpt:4.2.0
    container_name: mi-gpt
    network_mode: bridge
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
    env_file:
      - /volume1/docker/mi-gpt/.env
    volumes:
      - /volume1/docker/mi-gpt/.migpt.js:/app/.migpt.js
  mi-gpt-tts:
    image: idootop/mi-gpt-tts:3.0.0
    container_name: mi-gpt-tts
    network_mode: bridge
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
    env_file:
      - /volume1/docker/mi-gpt/.env
    ports:
      - "4322:3000"
  ```
