### ISSUE TITLE
tts 接口报错

### ISSUE THREAD

**Issue by Gcaufy** [idootop/mi-gpt-tts#14]
环境变量如下：

```
MI_USER=9xxxxxxxxxxxxxx
MI_PASSWORD=xxxxxxxxxxxxxxxxxxxxxx

OPENAI_API_KEY=sk-xxxxxxxxxxxxxxxxxxx
OPENAI_MODEL=xxxxxxxxxxxxxxxxxxxx
OPENAI_BASE_URL=https://xxxxxxxxxxxxxxxx


VOLCANO_TTS_USER_ID=xxxxxxxxxxxxxx
VOLCANO_TTS_APP_ID=xxxxxxxxxxxxxxxx
VOLCANO_TTS_ACCESS_TOKEN=xxxxxxxxxxxxxxxxx
TTS_DEFAULT_SPEAKER=BV051_streaming
TTS_BASE_URL=http://localhost:3000/xxxxxxxxxxx/api
SECRET_PATH=xxxxxxxxxxxxx
```

启动如下：

```
version: '3.0'
services:
   migpt:
    image: docker.unsee.tech/idootop/mi-gpt:latest
    container_name: migpt
    env_file: /opt/migpt/.env
    network_mode: host
    restart: always
    volumes:
       - /opt/migpt/.migpt.js:/app/.migpt.js
   migpt-tts:
    image: docker.unsee.tech/idootop/mi-gpt-tts:latest
    container_name: migpt-tts
    env_file: /opt/migpt/.env
    network_mode: host
    restart: always
```

报错日志如下：
```
🔥 /api/tts.mp3
e7ebe74e ❌ Volcano | Error code: 3001 {"reqid":"e93edd6c-6bb2-4604-ac23-0e4b52b093b3","message":"extract request resource id: get resource id: access denied","code":403,"backend_code":0}
🔥 /api/tts.mp3
6b7541af ❌ Volcano | Error code: 3001 {"reqid":"531e4e4c-3c78-4616-983e-aedc6bc9f8f5","message":"extract request resource id: get resource id: access denied","code":403,"backend_code":0}
```
